---
name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docker:
    name: Release Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Build and Push (latest)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: muhlba91/pdns-auth:latest

      - name: Build and Push (version)
        uses: docker/build-push-action@v2
        if: github.ref != 'refs/heads/master'
        with:
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: muhlba91/pdns-auth:${{ env.GITHUB_REF_SLUG }}

      - name: Update Description
        uses: peter-evans/dockerhub-description@v2
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: muhlba91/pdns-auth

      - name: Release
        uses: ncipollo/release-action@v1
        if: github.ref != 'refs/heads/master'
        with:
          name: ${{ env.GITHUB_REF_SLUG }}
          token: ${{ secrets.GITHUB_TOKEN }}
